language: java
jdk:
  - openjdk11

# travis ci server home
cache:
  directories:
    - '$HOME/.gradle'

script: "gradlew build"

before_install:
  - chmod +x ./gradlew

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: yuz-travis-vv
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yuz-travis-vv
    application: software-vv
    deployment_group: software-vv-group
    region: ap-northeast-2
    wait_until_deployed: true
